name: Start Tests
on:
  push:
    branches:
      - ASP.NET.WebForms
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x
    - name: Restore dependencies
      run: nuget restore CustomerClassLibrary.sln
    - name: Build
      run: msbuild
    - name: Test
      run: dotnet test ./tests/CustomerClassLibrary.Tests /p:Exclude="[*CustomerClassLibrary.Data]*" /p:ExcludeByFile=**/CustomerClassLibrary.Test/*.cs
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./tests/CustomerClassLibrary.Test/TestResults/coverage.opencover.xml
        flags: unittests 
        name: codecov-umbrella
        fail_ci_if_error: true 
        
        verbose: true
            
