name: Start Tests
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Tests
        run: |
          dotnet test --collect:"XPlat Code Coverage"
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./Customer Class Library.Test/TestResults/**/coverage.cobertura.xml
